server:
  port: 3344

spring:
  application:
    name:  microservicecloud-config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/JialuoFeng/microservicecloud-config.git #GitHub上面的git仓库名字
          username: net58740099@gmail.com
          password: lalalaKKKK1
 

